runtime: python37
service: default

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
  secure: always

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: secrets/firestore-auth.json

  MS_CLIENT_ID: <hidden>
  MS_CLIENT_SECRET: <hidden>
  GOOGLE_CLIENT_ID: <hidden>
